### ISSUE TITLE
After building ss2d and add PYTHONPATH, got ss2d.so error when "import ss2d"

### ISSUE THREAD

**Issue by CAJvon** [RobustFieldAutonomyLab/em_exploration#7]
Hello, appreciate for great work!

I met problem when run isrr2017.py.

Error info lists below, please help me~

```
$ echo $PYTHONPATH

/opt/ros/melodic/lib/python2.7/dist-packages:/media/Temp/debug_ws/em_exploration/build

$ python ../scripts/isrr2017.py 

Traceback (most recent call last):
  File "../scripts/isrr2017.py", line 2, in <module>
    from pyplanner2d import *
  File "/media/cajvon/Temp/debug_ws/em_exploration/scripts/pyplanner2d.py", line 6, in <module>
    from pyss2d import *
  File "/media/cajvon/Temp/debug_ws/em_exploration/scripts/pyss2d.py", line 7, in <module>
    import ss2d
ImportError: /media/cajvon/Temp/debug_ws/em_exploration/build/ss2d.so: undefined symbol: _ZNK5gtsam5Pose214transform_fromERKNS_6Point2ENS_16OptionalJacobianILi2ELi3EEENS4_ILi2ELi2EEE

```
Maybe the problem is about gtsam version?

**Comment by CAJvon** [comment]
I changed to gtsam-4.0.0-alpha2 and solved problem.
